name: Production Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install and setup Node version
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"
          cache: "npm"
      - name: Setup the AWS Cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1a
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: npm ci
      - run: NODE_ENV=production npm run build --if-present
      - run: aws s3 sync ./strapi s3:// --quiet --delete
